import type { Metadata } from "next";
import QueryClientProvider from "@/providers/QueryClientProvider";
import "./globals.css";
// import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
// import DisableWorkbox from "@/components/common/disableWorkbox";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // useEffect(() => {
  //   if (window !== undefined) {
  //     // eslint-disable-next-line @typescript-eslint/no-explicit-any
  //     const errorhandler = (event: any) => {
  //       console.error("event :", event);
  //       console.error("event.message:", event.message);
  //     };
  //     window.addEventListener("error", errorhandler);
  //     return () => {
  //       window.removeEventListener("error", errorhandler);
  //     };
  //   }
  // }, []);
  // useEffect(() => {
  //   if (typeof window !== "undefined") {
  //     // eslint-disable-next-line @typescript-eslint/no-explicit-any
  //     const errorHandler = (event: any) => {
  //       console.error("event:", event);
  //       console.error("event.message:", event.message);
  //     };

  //     const rejectionHandler = (event: PromiseRejectionEvent) => {
  //       console.error("Unhandled Promise Rejection:", event.reason);
  //     };

  //     window.addEventListener("error", errorHandler);
  //     window.addEventListener("unhandledrejection", rejectionHandler);

  //     return () => {
  //       window.removeEventListener("error", errorHandler);
  //       window.removeEventListener("unhandledrejection", rejectionHandler);
  //     };
  //   }
  // }, []);
  return (
    <html lang="en">
      <body suppressHydrationWarning className="antialiased">
        <QueryClientProvider>
          {/* <DisableWorkbox /> */}
          {/* <ReactQueryDevtools initialIsOpen={false} /> */}
          {children}
        </QueryClientProvider>
      </body>
    </html>
  );
}
